query($slug: String) {
    recipe(slug: $slug ){
      id
      slug
      name
      description
      body
      portions
      difficulty
      timeNeed
      tags {
        id
        slug
        name
      }
  }
}
