query($slug: String) {
    tag(slug: $slug ){
      id
      slug
      name
      recipes {
        id
        slug
        name
        description
        portions
        timeNeed
        difficulty
      }
  }
}
